'use client'
import { useEffect, useState } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [tabName, setTabName] = useState('hello')
  // const router = useRouter()
  // useEffect(() => {
  //   // if (!router.query)
  //     // router.push('/hello')
  // })
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-full flex flex-col justify-between" style={{ background: '#011627', border: '1px solid #1E2D3D', borderRadius: '8px' }}>
          <div className='flex w-full items-center justify-between tab-bordered'>
            <div className="tabs  flex" >
              <Link href={'/amine-haddad'} className={`tab h-[50px]  ${tabName === 'me' ? 'tab-active  tab-bordered  border-myorange' : ''} `} onClick={() => { setTabName('me') }}>amine-haddad</Link>
              <div className="divider lg:divider-horizontal m-0"></div>
              <Link href={'/hello'} className={`tab h-[50px]  ${tabName === 'hello' ? 'tab-active tab-bordered border-myorange' : ''} `} onClick={() => setTabName('hello')}>_hello</Link>
              <div className="divider lg:divider-horizontal"></div>
              <Link href={'/aboutme'} className={`tab h-[50px]  ${tabName === 'about' ? 'tab-active tab-bordered border-myorange' : ''} `} onClick={() => setTabName('about')}>_about-me</Link>
              <div className="divider lg:divider-horizontal"></div>
              <Link href={'/projects'} className={`tab h-[50px]  ${tabName === 'projects' ? 'tab-active tab-bordered border-myorange' : ''} `} onClick={() => setTabName('projects')}>_projects</Link>
              <div className="divider lg:divider-horizontal"></div>
            </div>
            <div className="tabs" >
              <div className="divider lg:divider-horizontal"></div>
              <Link href={'/contactme'} className={`tab h-[50px] ${tabName === 'contact' ? 'tab-active tab-bordered border-myorange' : ''} `} onClick={() => setTabName('contact')}>_contact-me</Link>
            </div>
          </div>
          {children}
          <div className='bottom-0 flex w-full items-center justify-between border-t-[1px] border-t-bordercolor'>
            <div className="tabs devide-x-[2px]" >
              <Link href={'/'} className={`tab h-[50px]  ${tabName === 'findme' ? 'tab-active tab-bordered border-myorange' : ''} `} onClick={() => setTabName('findme')}>find me in:</Link>
              <div className="divider lg:divider-horizontal"></div>
              <Link href={'/'} className={`tab h-[50px]  ${tabName === 'gmail' ? 'tab-active tab-bordered border-myorange' : ''} `} onClick={() => setTabName('gmail')}>gmail</Link>
              <div className="divider lg:divider-horizontal"></div>
            </div>
            <div className="tabs" >
              <div className="divider lg:divider-horizontal"></div>
              <Link href={'/'} className={`tab h-[50px]  ${tabName === 'ahaddad' ? 'tab-active tab-bordered border-myorange' : ''} `} onClick={() => setTabName('ahaddad')}>@ahaddad</Link>
            </div>
          </div>
        </main>
      </body>
    </html>
  )
}
