'use client'
import { useEffect, useState } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { MyGlobalProvider } from './ContextGlobalProvider'
import LayoutComponent from './LayoutComponent'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <MyGlobalProvider>
      <LayoutComponent children={children} />
    </MyGlobalProvider>
  )
}
